craftworkgames/MonoGame.Extended

MonoGame.Extended/MonoGame.Extended/Camera2D.cs

This pull request fulfills #1 (Adding camera functionality). It add methods for creating a BoundingFrustum and checking if points are contained in the camera view.

Camera utility features

---

MonoGame.Extended/MonoGame.Extended/Camera2D.cs

Well... this proves that I need to stop coding for tonight. I should have caught this.
Again, I apologize.

Fixing hardcoded rectangle values

---

Source/MonoGame.Extended/InputEvents/Input.cs
Source/MonoGame.Extended/InputEvents/MonoGame.Input/EventArgs/MonoGameMouseEventArgs.cs
Source/MonoGame.Extended/InputEvents/MonoGame.Input/Keyboard/MonoGameMouseEvents.cs
Source/MonoGame.Extended/InputEvents/MonoGame.Input/Mouse/MonoGameMouseEvents.cs
Source/MonoGame.Extended/InputEvents/MonoGame.Input/Touch/MonoGameTouchEvents.cs
Source/MonoGame.Extended/InputEvents/MonoGameInput.cs
Source/MonoGame.Extended/InputEvents/README.md
Source/MonoGame.Extended/InputEvents/Shared/EventArgs/KeyboardCharacterEventArgs.cs
Source/MonoGame.Extended/InputEvents/Shared/EventArgs/KeyboardKeyEventArgs.cs
Source/MonoGame.Extended/InputEvents/Shared/EventArgs/MouseEventArgs.cs
Source/MonoGame.Extended/InputEvents/Shared/EventArgs/TouchEventArgs.cs
Source/MonoGame.Extended/InputEvents/Shared/Keyboard/KeyboardUtil.cs
Source/MonoGame.Extended/InputEvents/Shared/Keyboard/Modifiers.cs
Source/MonoGame.Extended/InputEvents/Shared/Mouse/MouseButton.cs
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/Sandbox/SandboxGame.cs

Added event driven input library.
Altered sandbox to use the event driven input library.
Merge commit for issue: https://github.com/craftworkgames/MonoGame.Extended/issues/14/

MonoGame-EventDriven-Input pull request.

---

Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/MonoGame.Extended.Tests/Shapes/CircleTest.cs
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/Shapes/Circle.cs

Added the circle as discussed in https://github.com/craftworkgames/MonoGame.Extended/issues/43

Added Circle

---

Source/MonoGame.Extended/FPSCounter.cs
Source/MonoGame.Extended/MonoGame.Extended.csproj

Added FPS Counter

---

Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/Sprites/Animation.cs
Source/MonoGame.Extended/Sprites/AnimationExtension.cs
Source/MonoGame.Extended/Sprites/Sprite.cs

Added Animation class

---

Source/MonoGame.Extended/Sprites/Animation.cs
Source/MonoGame.Extended/Sprites/AnimationExtension.cs
Source/MonoGame.Extended/Sprites/SpriteExtensions.cs

Stuff done:
- removed initalizrs for fields that are gonna get those values regardless
- added the ability to modify sprites in animation as well as to add / remove them
- added animation position
- added ability to read spritesheet up-down instead of just being able to read left-right
- should I maybe allow reading right-left and bottom-up? never saw anyone use those but still...
https://youtu.be/hc4_hqe87UE

Updated Animation stuff

---

Documentation/MonoGamePCL.md

Here they are! I found some time at school today to write these today; they should be detailed enough.
Completes https://github.com/craftworkgames/MonoGame.Extended/pull/26.
Referencing https://github.com/mono/MonoGame/issues/3944 for the record.

Adding docs about how to build a Monogame PCL

---

README.md

https://github.com/craftworkgames/MonoGame.Extended/issues/55

Update README.md to include logo

---

README.md

Fulfills https://github.com/craftworkgames/MonoGame.Extended/issues/68.

Added feature list (sorted by version)

---

Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs

TiledMap background color now being rendered

---

Source/MonoGame.Extended/Shapes/RectangleF.cs

Allows RectangleF to be explicitly cast to Rectangle.

Add cast operators to and from Rectangle

---

Source/MonoGame.Extended/Sprites/Sprite.cs
Source/MonoGame.Extended/Sprites/SpriteBatchExtensions.cs

Now you can change the opacity of a sprite.

Add alpha feature to Sprites

---

Source/MonoGame.Extended.Tests/Collections/PoolTests.cs

Sorry I forgot to commit this one file :cry:

Object pool tests

---

Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/MonoGame.Extended.Tests/RangeTest.cs
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/Range.cs

This adds `Range<T>` to the core library #174. The random values are left out because those are still in the Tweening branch.

Add range<T>

---

Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/MonoGame.Extended.Tests/Particles/AssertionModifier.cs
Source/MonoGame.Extended.Tests/Particles/ColourTests.cs
Source/MonoGame.Extended.Tests/Particles/EmitterTests.cs
Source/MonoGame.Extended.Tests/Particles/ParticleBufferTests.cs
Source/MonoGame.Extended.Tests/Particles/Profiles/PointProfileTests.cs
Source/MonoGame.Extended.Tests/Particles/Profiles/RingProfileTests.cs
Source/MonoGame.Extended/Particles/HslColor.cs
Source/MonoGame.Extended/Particles/LineSegment.cs

fixes #197
Ported the ones that were there, I'll also add some for the modifiers and interpolation modifiers.

Particle tests

---

Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs

fixed issue #211 - tilemap height can now be higher than wide

---

Source/MonoGame.Extended/Particles/HslColor.cs
Source/MonoGame.Extended/Serialization/SizeFJsonConverter.cs
Source/MonoGame.Extended/Serialization/Vector2JsonConverter.cs

Hello,
I'm on a french environment, and I have this System.FormatException when I try to run some examples due to float parsing (in french, float numbers use comma). This commit is enough to solve this issue.
Keep up the good work ;)

Fix System.FormatException thrown during float parsing

---

Source/MonoGame.Extended.Content.Pipeline.Tests/MonoGame.Extended.Content.Pipeline.Tests.csproj
Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/MonoGame.Extended.Tests/Shapes/RectangleFTests.cs
Source/MonoGame.Extended.Tests/SizeFTests.cs
Source/MonoGame.Extended/SizeF.cs

Added implicit operator to Monogame.Extended.SizeF which casts Vector2 to SizeF.

SizeF class implicit operator added

---

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs
Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs
Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs
Source/MonoGame.Extended/Maps/Tiled/TiledTileSetTile.cs

Reverts craftworkgames/MonoGame.Extended#246

Revert "Objectgroups for Tiles!"

---

README.md

Mention @prime31 's Nez library in README

Add Nez mention to README

---

Source/Demos/Demo.TiledMaps/Content/level01.tmx
Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs
Source/MonoGame.Extended.Content.Pipeline/Tiled/TmxLayer.cs
Source/MonoGame.Extended/Maps/Tiled/TiledLayer.cs
Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs
Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs

Support to layers offset

---

Source/Demos/Demo.SpaceGame/Entities/Explosion.cs
Source/Demos/Demo.SpriteSheetAnimations/Game1.cs
Source/Demos/Demo.SpriteSheetAnimations/Zombie.cs
Source/Demos/Demo.TiledMaps/Game1.cs
Source/MonoGame.Extended.Tests/AngleTest.cs

While browsing the demos I noticed that some code was following the obsolete method of doing things, so I modified them. It all seems to be straightforward so there shouldn't be any problems but you never know.
Also sorry about the useless Unit Test commits that don't do anything... I was testing something out and I totally forgot to remove them...
edit: By the way, it doesn't really have anything to do with this (well except for my mistakes...) but the `AngleTest.cs` unit tests work fine on my machine.

Changed obsolete demo code

---

README.md
Source/MonoGame.Extended.Tests/AngleTest.cs

Just trying to trigger a PR for the build system

---

Source/Demos/Demo.Gui/Demo.Gui.csproj
Source/Demos/Demo.Gui/packages.config
Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj
Source/MonoGame.Extended.Content.Pipeline/packages.config
Source/MonoGame.Extended.Graphics.nuspec
Source/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj
Source/MonoGame.Extended.Gui/packages.config
Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/MonoGame.Extended.Tests/packages.config
Source/MonoGame.Extended.Tiled.nuspec
Source/MonoGame.Extended.nuspec
Source/MonoGame.Extended.sln
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/packages.config

-Upgrade JSON.NET to latest stable for all projects.
-Add some experimental NuGet packages. @craftworkgames You will probably need to double check the `.nuspec` files are correct and do work correctly.

JSON.NET & .nuspecs

---

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImporter.cs

Fixes #361.
Check if anything else is needed please.

- Fix Tileset.FirstGlobalIdentifier

---

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImporter.cs

Reverts craftworkgames/MonoGame.Extended#362

Revert "- Fix Tileset.FirstGlobalIdentifier"

---

Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj
Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapTile.cs
Source/MonoGame.Extended.Tiled/Tiled/TiledMapTileLayer.cs
Source/MonoGame.Extended.Tiled/Tiled/TiledMapTileObject.cs

Change TiledMapTileLayer to store blank tiles so that TryGetTile returns the correct TiledMapTile instances (#352).

Fix TryGetTile

---

Source/MonoGame.Extended.Particles/Particle.cs
Source/MonoGame.Extended.Particles/ParticleEffect.cs
Source/MonoGame.Extended.Particles/ParticleEmitter.cs
Source/MonoGame.Extended.Particles/ParticleExtensions.cs

This work is in regards to Issue #381

add LayerDepth to Particles

---

Source/NuGet/MonoGame.Extended.Animations.nuspec
Source/NuGet/MonoGame.Extended.Entities.nuspec
Source/NuGet/MonoGame.Extended.Graphics.nuspec
Source/NuGet/MonoGame.Extended.Gui.nuspec
Source/NuGet/MonoGame.Extended.Input.nuspec
Source/NuGet/MonoGame.Extended.NuclexGui.nuspec
Source/NuGet/MonoGame.Extended.Particles.nuspec
Source/NuGet/MonoGame.Extended.SceneGraphs.nuspec
Source/NuGet/MonoGame.Extended.Tiled.nuspec
Source/NuGet/MonoGame.Extended.Tweening.nuspec
Source/NuGet/MonoGame.Extended.nuspec

Modified nuspec definitions to conform to [nuspec convention to target multiple platforms](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) as described in issue #383

Fixed nuspec definitions

---

Docs/MonoGame.Extended/Content.md
mkdocs.yml

Added some examples on how to use the `ContentManager` and `ContentReader` extensions.

[Docs] Added Content Extensions

---

Docs/Community-and-Support.md
Docs/MonoGame.Extended/Camera2D.md
Docs/index.md
README.md

Changed wiki references to github.io docs site.
Added "Docs" badge at the top of README.md

[Docs] updating wiki references to new docs site.

---

Docs/MonoGame.Extended.Animation/Animated-Sprites.md
Docs/MonoGame.Extended/Camera2D.md
Docs/MonoGame.Extended/Collections.md
Docs/MonoGame.Extended/Object-Pooling.md
Docs/MonoGame.Extended/Screens.md

because C# randomly fails to format correctly.

Formatting code blocks with csharp

---

Source/MonoGame.Extended.Tiled/TiledMapTileObject.cs

added Tileset property to TiledMapTileObject

---

Source/MonoGame.Extended.Gui/Controls/GuiButton.cs
Source/MonoGame.Extended.Gui/Controls/GuiCheckBox.cs
Source/MonoGame.Extended.Gui/Controls/GuiComboBox.cs
Source/MonoGame.Extended.Gui/Controls/GuiControl.cs
Source/MonoGame.Extended.Gui/Controls/GuiForm.cs
Source/MonoGame.Extended.Gui/Controls/GuiItemsControl.cs
Source/MonoGame.Extended.Gui/Controls/GuiStackPanel.cs
Source/MonoGame.Extended.Gui/Controls/GuiSubmit.cs
Source/MonoGame.Extended.Gui/Controls/GuiTextBox.cs
Source/MonoGame.Extended.Gui/GuiScreen.cs
Source/MonoGame.Extended.Gui/GuiSystem.cs
Source/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj
Source/MonoGame.Extended.Gui/Serialization/GuiControlJsonConverter.cs
Source/MonoGame.Extended.Gui/Serialization/GuiSkinJsonConverter.cs
Source/Tests/Sandbox/Content/adventure-gui-screen.json
Source/Tests/Sandbox/Content/adventure-gui-skin.json
Source/Tests/Sandbox/Content/test-addition-screen.json
Source/Tests/Sandbox/Game1.cs
Source/Tests/Sandbox/Sandbox.csproj

The following changes were added
- 'Padding' attribute to the 'GuiStackPanel' and 'GuiTextbox'
- Selection to 'GuiTextbox'
- CustomTypes can be passed into the GuiScreen.FromFile
- MouseMoveEvent on GuiControls
- Propagation down the control tree
- 'GuiForm' and 'GuiSubmit' where the form will allow for tabbing between controls and the enter will trigger the submit button.

[GUI] Adding support for parent propegation, the idea of forms and textbox highlighting

---

Source/Demos/Demo.SpaceGame/Entities/Spaceship.cs
Source/Demos/Demo.SpaceGame/Game1.cs
Source/Demos/Demo.StarWarrior/packages.config
Source/MonoGame.Extended.Entities/EntityComponentSystem.cs

EntityTemplate.Manager wasn't assigned.
Fixes issue #445

Fix template manager

---

Source/MonoGame.Extended.Animations/MonoGame.Extended.Animations.csproj
Source/MonoGame.Extended.Collisions/MonoGame.Extended.Collisions.csproj
Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj
Source/MonoGame.Extended.Entities/MonoGame.Extended.Entities.csproj
Source/MonoGame.Extended.Graphics/MonoGame.Extended.Graphics.csproj
Source/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj
Source/MonoGame.Extended.Input/MonoGame.Extended.Input.csproj
Source/MonoGame.Extended.NuclexGui/MonoGame.Extended.NuclexGui.csproj
Source/MonoGame.Extended.Particles/MonoGame.Extended.Particles.csproj
Source/MonoGame.Extended.SceneGraphs/MonoGame.Extended.SceneGraphs.csproj
Source/MonoGame.Extended.Tiled/MonoGame.Extended.Tiled.csproj
Source/MonoGame.Extended.Tweening/MonoGame.Extended.Tweening.csproj
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/NuGet/MonoGame.Extended.Animations.nuspec
Source/NuGet/MonoGame.Extended.Entities.nuspec
Source/NuGet/MonoGame.Extended.Graphics.nuspec
Source/NuGet/MonoGame.Extended.Gui.nuspec
Source/NuGet/MonoGame.Extended.Input.nuspec
Source/NuGet/MonoGame.Extended.NuclexGui.nuspec
Source/NuGet/MonoGame.Extended.Particles.nuspec
Source/NuGet/MonoGame.Extended.SceneGraphs.nuspec
Source/NuGet/MonoGame.Extended.Tiled.nuspec
Source/NuGet/MonoGame.Extended.Tweening.nuspec
Source/NuGet/MonoGame.Extended.nuspec

Note that this does cause warnings to be generated for missing XML docs.

Added XML docs to NuGet

---

Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/Point2.cs
Source/MonoGame.Extended/Point3.cs
Source/MonoGame.Extended/Size3.cs

Implemented Size3 and Point3.  Fixed bug in Point2.
The documentation listed Point2, but code took in Vector2.  Changed to Point2

Implemented Size3 and Point3.  Fixed bug in Point2.

---

Docs/Monogame.Extended.Tiled/TiledMap.md

Created documentation for `MonoGame.Extended.Tiled`

Documentation for MonoGame.Extended.Tiled

---

Docs/MonoGame.Extended.Entities/Entity-Component-System.md

This the first draft, I documented it to the best of my knowledge, though I feel its still missing a lot. I will continue to make changes as my knowledge grows and as recommendations are made.

[WIP] First Draft of Entity-Component-System Documentation

---

Source/MonoGame.Extended/CircleF.cs
Source/Tests/MonoGame.Extended.Tests/Primitives/CircleFTests.cs

Fix circlef contains

---

Docs/Features/Tiled.md

Fixed the link to Pipeline tool setup

---

Docs/Documentation.md

Corrected spelling of "Documentation".

Fixed typo.

---

Source/MonoGame.Extended.sln

Hi, here's my first pull request, maybe there are some more following. The .nuspec files were incorporated into the .csproj files and were removed in a commit, but are still in the solution file. This PR fixes that.

removed non-existing .nuspec files from solution

---

Source/Demos/Platformer/Collisions/World.cs

- The equality check is a little gross for dynamicBody -> otherDynamicBody, but it works for now.
- Added notes about how I did this.
- Tested it with the current platformer demo

Added loop to handle dynamic -> dynamic body collision resolution

---

Source/MonoGame.Extended/Screens/ScreenManager.cs

as per request from http://community.monogame.net/t/screenmanager-wont-loadcontent/11043

Changed to call initialisation if not done

---

Source/MonoGame.Extended.Particles/ParticleBuffer.cs

Fixed the correct value passed to GC on Dispose of ParticleBuffer (#580)

---

Docs/Features/Cameras.md

Thanks for the awesome library!

Cameras.md typo:  too -> to

---

Source/MonoGame.Extended.Entities/EntityManager.cs

Notify subscribers before removing components from entity

---

Source/MonoGame.Extended/Math/ShapeExtensions.cs

Create a simple draw ellipse function. We use the parametric equation for the ellipse to create a list of vertices, and piggyback off of DrawPolygon.
Let me know what you think. This is the simplest implementation, but we could maybe improve performance if sin/cos are too slow. (I haven't profiled.)

Create function to draw an ellipse.

---

Source/Demos/Features/Demos/CollisionDemo.cs
Source/MonoGame.Extended.Collisions/QuadTree/CollisionComponent.cs

- Fix an issue with actor bounds not being set properly. This makes the collisions in the demo smoother.
- Improved the demo's code quality by adding some comments.

Improve collision demo

---

Source/MonoGame.Extended/Collections/Bag.cs

Make sure to clear the array before setting count to zero.

Fix Clear method

---

Source/MonoGame.Extended/Transform.cs

The comments of this file referenced a nonexistent "Transform3" class and I thought it would be useful for a project I'm trying to develop so I made an implementation of it using the Matrix class from XNA.

Implemented Transform3 class

---

Source/MonoGame.Extended.Input/InputListeners/KeyboardListener.cs

`Enum.GetValues` generates garbages.

Remove garbage generated in input listners

---

Docs/Features/Cameras.md
Docs/Features/Tiled.md

There has been a small refactor of the camera.
This PR just updates the docs to reflect that.

Update camera docs

---

Source/Demos/Tutorials/Content/adventure-gui-skin.json
Source/Demos/Tutorials/Content/title-screen.json
Source/MonoGame.Extended.Gui/Serialization/ControlJsonConverter.cs
Source/MonoGame.Extended.Gui/Serialization/ControlStyleJsonConverter.cs
Source/MonoGame.Extended.Gui/Serialization/GuiJsonSerializer.cs
Source/MonoGame.Extended.Gui/Skin.cs
Source/MonoGame.Extended/Serialization/Size2JsonConverter.cs
Source/MonoGame.Extended/Serialization/SizeJsonConverter.cs

This PR starts fixing the Gui system (see #552). I hope the fixes go into the proper direction. I reintroduced the Dialog and Image classes so that loading the skin file can find the C# classes. The GUI demo feature now starts, but doesn't properly show the three buttons, and I don't know yet why.
Comments welcome!

Gui System fixes

---

Source/Demos/Tutorials/Content/TiledMaps/level01.tmx
Source/MonoGame.Extended.Tiled/Serialization/TiledMapPropertyContent.cs

TiledMap property multi-line bug fix

---

Source/Demos/Tutorials/Demos/ShapesDemo.cs
Source/MonoGame.Extended/Math/Triangulation/CyclicalList.cs
Source/MonoGame.Extended/Math/Triangulation/IndexableCyclicalLinkedList.cs
Source/MonoGame.Extended/Math/Triangulation/LineSegment.cs
Source/MonoGame.Extended/Math/Triangulation/Triangle.cs
Source/MonoGame.Extended/Math/Triangulation/Triangulator.cs
Source/MonoGame.Extended/Math/Triangulation/Vertex.cs
Source/MonoGame.Extended/VectorDraw/PrimitiveBatch.cs
Source/MonoGame.Extended/VectorDraw/PrimitiveDrawing.cs

This PR contains an implementation using a PrimitiveBatch in lieu of a ShapeBatch for drawing additional shapes.  These shapes include: 
- Points
- Rectangles
- Filled Rectangles
- Circles
- Filled Circles
- Line Segments
- Polygons
- Filled Polygons
The polygon implementation using the ear clipping method.  I made every attempt to keep the code format consistent and updated the Tutorial Shapes project with an example of usage.

Additional Shapes - Issue 629

---

Docs/Features/Animations.md
Docs/Features/Input.md

Also fixed some typos/grammatical errors in the Animations docs

Started some docs for Input

---

Source/MonoGame.Extended.Gui/Controls/LayoutControl.cs
Source/MonoGame.Extended.Gui/Controls/UniformGrid.cs

-Fix for issue https://github.com/craftworkgames/MonoGame.Extended/issues/601
-Added offset for UniformGrid

#601 [GUI] Padding fix, Uniform grid padding offset

---

Source/MonoGame.Extended/Math/RectangleF.cs

There was a TopLeft and a BottomRight, but no TopRight or BottomLeft... But there could be. :)

Add RectangleF.TopRight

---

README.md

Since the project has been handed over to @lithiumtoast, the handover note is no longer relevant.

removed ownership handover note

---

Source/MonoGame.Extended/Collections/ObjectPool.cs

Set capacity for ObjectPool in the constructor

---

Source/Games/Platformer/EntityFactory.cs

Fix missing animations in Platformer sample game

---

Source/MonoGame.Extended.Collisions/MonoGame.Extended.Collisions.csproj
Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj
Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapProcessor.cs
Source/MonoGame.Extended.Entities/MonoGame.Extended.Entities.csproj
Source/MonoGame.Extended.Graphics/MonoGame.Extended.Graphics.csproj
Source/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj
Source/MonoGame.Extended.Input/MonoGame.Extended.Input.csproj
Source/MonoGame.Extended.NuclexGui/MonoGame.Extended.NuclexGui.csproj
Source/MonoGame.Extended.Particles/MonoGame.Extended.Particles.csproj
Source/MonoGame.Extended.SceneGraphs/MonoGame.Extended.SceneGraphs.csproj
Source/MonoGame.Extended.Tiled/MonoGame.Extended.Tiled.csproj
Source/MonoGame.Extended.Tweening/MonoGame.Extended.Tweening.csproj
Source/MonoGame.Extended/MonoGame.Extended.csproj
Source/MonoGame.Extended/TextureAtlases/TextureAtlasJsonContentTypeReader.cs
Source/Tests/MonoGame.Extended.Collisions.Tests/MonoGame.Extended.Collisions.Tests.csproj
Source/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/MonoGame.Extended.Content.Pipeline.Tests.Tiled.csproj
Source/Tests/MonoGame.Extended.Content.Pipeline.Tests/MonoGame.Extended.Content.Pipeline.Tests.csproj
Source/Tests/MonoGame.Extended.Entities.Tests/MonoGame.Extended.Entities.Tests.csproj
Source/Tests/MonoGame.Extended.Gui.Tests/MonoGame.Extended.Gui.Tests.csproj
Source/Tests/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj
Source/Tests/MonoGame.Extended.Tiled.Tests/MonoGame.Extended.Tiled.Tests.csproj

Update to use MonoGame 3.8 NuGet packages

---

src/dotnet/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImporter.cs

Resolve relative paths for tileset sources in tiled map importer

---

src/cs/MonoGame.Extended.Entities/ComponentMapper.cs
src/cs/Tests/MonoGame.Extended.Entities.Tests/ComponentMapperTests.cs

Added a on put and on delete event on component mapper

---

src/cs/MonoGame.Extended.Input/KeyboardExtended.cs
src/cs/MonoGame.Extended.Input/MouseExtended.cs

I forgot to add return types in my last PR and broke all builds))

Fixed return types absence.

---

src/cs/MonoGame.Extended.Entities/ComponentManager.cs
src/cs/Tests/MonoGame.Extended.Entities.Tests/WorldManagerTests.cs

Bugfix null ptr on destroy

---

src/cs/MonoGame.Extended.Input/InputListeners/KeyboardListener.cs

Reverts craftworkgames/MonoGame.Extended#831

Revert "Add copy constructor for KeyboardListener."

---

src/cs/MonoGame.Extended/HslColor.cs

Fixed a single-digit typo as per the suggestion in issue #809

Fixed HSL Lerp function

---

.github/workflows/develop-build.yml

Fixes the nuget push for github

Fix GitHub Nuget Push

---

.github/workflows/develop-build.yml

Removing github nuget deploy until settings in repository can be updated.

Remove GitHub Deploy

---

.github/FUNDING.yml

Fixes funding so more than one displays

Fix funding

---

.github/workflows/create-release.yml

Adds additional input parameters to the create-release workflow

Add additional input parameters

---

.github/workflows/create-release.yml

Updates create-release workflow to only specify prerelase and source.

Only specify source and prerelease

---

README.md

Updates the prerelease version number in the Readme

Update prerelease version

---

CHANGELOG.md

Make links for users

---

source/MonoGame.Extended/Math/Matrix3x2.cs

fix(Matrix3x2): decompose method

---

source/MonoGame.Extended/Graphics/Sprite.cs

Revert the changes that are breaking Origin's value. Fixes #950

Revert UV code

---

.github/workflows/create-release.yml
.github/workflows/pull-request-test.yml
CHANGELOG.md
Directory.Build.props
source/MonoGame.Extended/BitmapFonts/BitmapFont.cs
source/MonoGame.Extended/Content/BitmapFonts/BitmapFontFileReader.cs
source/MonoGame.Extended/Graphics/NinePatch.cs
source/MonoGame.Extended/Graphics/Sprite.cs
source/MonoGame.Extended/Graphics/Texture2DRegion.Extensions.cs
source/MonoGame.Extended/Math/Matrix3x2.cs
tests/MonoGame.Extended.Tests/BitmapFonts/BitmapFontFileReaderTests.cs

Version 4.0.3
