craftworkgames/MonoGame.Extended

MonoGame.Extended/MonoGame.Extended/Camera2D.cs
Welp. I've learned my lesson. Always compile before that last push.
This fixes all compile errors.
=> Fixing Contains overloads failing to compile because of duplicate method sigs.

README.md
There was one hidden in the Contributing section before, but it wasn't very visible.
=> Added usage/link to samples that's not hidden

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImporter.cs
The content pipeline extension was throwing an exception when one tried to build a .tmx Tiled map file with a tileset that pointed to an external .tsx file. The fix checks for such tilesets, deserializes the external file and replaces the one in the main map instance.
=> Tilset importer fix for external .tsx tilesets

Source/MonoGame.Extended/Maps/Tiled/TiledLayer.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj, Source/MonoGame.Extended/ViewportAdapters/WindowViewportAdapter.cs
I use <kbd>Ctrl + K, D</kbd> a lot out of habit, so it added a little formatting to a couple of things.
TiledTileLayer:
* The obsolete method `Draw(Camera2D camera)` no longer obsolete
TiledLayer:
* The obsolete method `Draw(Camera2D camera)` no longer obsolete.
* Implemented `Draw(Camera2D camera)` so that it only renders tiles within the camera's bounds.
=> Draw method update for TiledLayer and TiledTileLayer

README.md, Source/MonoGame.Extended/InputListeners/GamePadEventArgs.cs, Source/MonoGame.Extended/InputListeners/GamePadListener.cs, Source/MonoGame.Extended/InputListeners/GamePadListenerSettings.cs, Source/MonoGame.Extended/InputListeners/InputListenerManager.cs
Hey guys.
I've been using Monogame.Extended in a school project, and I'm very happy with it. However, one feature was missing in particular to me, which was a `GamePadListener`. So I decided to implement one myself.
The functionality is very much complete. It has several events for buttons going up, down, being held down, thumbsticks moving, triggers moving, controllers connecting and disconnecting.
There is an extensive associated settings class that allows users to fine-tune the behaviour of the listener. It even has a very simple public method to set a vibration that is very much "fire and forget" (the listener brings the vibration down for you, using a duration parameter, instead of having to manually set both vibes to 0). About the only thing that doesn't work is multiple buttons …
=> New functionality: GamePadListener

Source/MonoGame.Extended/ViewportAdapters/BoxingViewportAdapter.cs
Hi,
I managed to find a bug in the `BoxingViewportAdapter` with DirectX rendering, annoyingly it works with MonoGame.Linux and MonoGame.OpenGL without problems.
But with MonoGame.DirectX the PrefferedBackBufferSize isn't correctly updated when the window is resized, which results in a distortion of the rendering.
*(see: http://gfycat.com/BasicLegalHerculesbeetle)*
To fix this the PrefferedBackBufferSize has to be manually updated.
*(http://gamedev.stackexchange.com/questions/68914/issue-with-monogame-resizing)*
The `BoxingViewportAdapter` now needs to get a `GraphicsDeviceManager` in its constructor instead of an `GraphicsDevice`. Perhaps that should be changed in the other Adapters too. So that the interface stays symmetrical? If you want I can change that in this pull request too. …
=> Fixed BoxingViewportAdapter for DirectX Rendering

Source/MonoGame.Extended/Camera2D.cs
Fixed: when using a BoxingViewportAdapter, the tiles are not drawn correctly: http://i.imgur.com/2uWX1fW.gif
=> Fix ViewMatrix bug with BoxingViewportAdapter

Source/Demo.TiledMaps/Content/level01.tmx, Source/Demo.TiledMaps/Game1.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TmxObject.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledObject.cs, Source/MonoGame.Extended/Maps/Tiled/TiledObjectGroup.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileSet.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj, Source/Sandbox/SandboxGame.cs
Which features it supports at the moment:
- Get Object Groups
- Get objects from Object Groups
- Get the `GID`, `X`, `Y`, `Width` and `Height` from an object
- Read properties from Object Layers and Objects
Known issues:
- The values from XML can't contains points.
Example:
<object id="5" gid="26" x="128" y="896" width="297" height="342">
Acceptable.
<object id="5" gid="26" x="88.6061" y="880.848" width="297" height="342">
Unnaceptable, raises an error. I know the error comes from `TmxObject.cs`, the values aren't integers. If I change from integer to double or float, the values comes wrong. Changing the type of `y` from int to float:
[XmlAttribute(DataType = "float", AttributeName = "y")]
public float Y { get; set; }
Result:
=> Support to Object Layers

Source/MonoGame.Extended/Collections/Deque.cs
Check if the item is at the front or back of the `Deque` before checking the whole circular array. This is important for `Pool`.
=> hotfix Deque IndexOf

Source/Demos/Demo.SpriteSheetAnimations/Game1.cs, Source/Demos/Demo.TiledMaps/Game1.cs, Source/MonoGame.Extended/FramesPerSecondCounter.cs, Source/MonoGame.Extended/FramesPerSecondCounterComponent.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj
I find it confusing to call `fpsCounter.Update()` in a Draw loop.
As a GameComponent, the user doesn't have to worry about forgetting to call `fpsCounter.Update`, or calling Update in the wrong loop.
=> Make FPS counter a GameComponent

Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontReader.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontRegion.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj
The .NET Char type currently used to identify a glyph in a BitmapFont is
limited to 16 bits, while some Unicode characters (surrogate pairs,
which include Emoji) require 32 bits.
The fix is to use the Int32 type to represent a Unicode character, and
to parse UTF-16 .NET input strings as 32-bit Unicode code point
sequences.
=> Support Unicode emoji characters in BitmapFont

Source/Demos/Demo.ViewportAdapters/Game1.cs, Source/MonoGame.Extended/ViewportAdapters/BoxingViewportAdapter.cs
This PR adds support for bleed areas as discussed in #159.
Both constructors are overloaded with additional horizontal/vertical bleed parameters. 
I have also added None value to the BoxingMode enum which is set when no letterboxing (or pillarboxing) occurs.
=> Add support for defining bleed areas in BoxingViewportAdapter

Source/MonoGame.Extended.Tests/AngleTest.cs, Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj, Source/MonoGame.Extended/Angle.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj, Source/MonoGame.Extended/Particles/Modifiers/Interpolators/ColorInterpolator.cs, Source/MonoGame.Extended/Particles/Modifiers/Interpolators/HueInterpolator.cs
This struct is based on the one from xenko engine, it allows you to use the unit type you want for angles. Supported unit types are: radians, degrees, gradians and revolutions.
It has methods to wrap (between -pi and pi) or to wrap positive (between 0 and 2*pi).
It also has methods to get the angle from a vector, and to create a vector (unit or specified length) from an angle.
Reasoning behind using a double for the value is because all the .net angle math functions use doubles, this will allow for less casts and higher precision.
=> Angle struct

Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs
- Calculate correct TiledTileSetTile id inside TileSet. (Due to documentation Tile id is local id inside TileSet http://doc.mapeditor.org/reference/tmx-map-format/), this will correctly render animation if several tilesets used in map.
- Fix tile animation rendering. Prevent first frame of the animation tile to be always rendered.
=> Tiled map: Fix for Tile Id and Tile animation.

Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs
I've noticed what appears to be a bug in the MonoGame.Extended Tiled layer rendering.
Here is what my map looks like in Tiled
Here is what my map looks like in the game:
The difference appears to be that MonoGame.Extended draws the tile sprite from the top left corner of the tile, while Tiled itself draws sprites from the bottom left corner (going up) of its tiles.
=> Bug: Adjust tiled tiles to effectively draw from lower left corner

Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs
I wrote this because if a tilesheet is stored inside a Tiled Map file, there is currently no publicly acessible way to access the TiledTileSheet object for that tilesheet with only a reference to a TiledMap. This means that if there are properties stored inside a tilesheet that is inside a map, there is NO WAY to access them.
I've never done a PR before, so forgive me if I've done something wrong, but as far as I've seen, this shouldn't affect anything else...
=> Modify TiledMap to expose the list of its tilesets publicly.

Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs
I found an issue while trying to position text according to its width. There would be an extra amount of width, coming from the `XAdvance` property for the last character. Since the last character is not advancing to another we should use the sum of the character region's `XOffset` and `Width` instead.
=> correct width calculation for bitmap fonts

Source/Demos/Demo.BitmapFonts/Game1.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs
As mentioned in https://github.com/craftworkgames/MonoGame.Extended/pull/225.
Adds letter spacing support to the BitmapFont class through a public `LetterSpacing` property, defaulting to 0 and thus backwards compatible.
LetterSpacing indicates inter-character space in addition to the default space between characters.
=> Add LetterSpacing to BitmapFont

Source/Demos/Demo.SceneGraphs/Game1.cs, Source/MonoGame.Extended/Matrix2D.cs, Source/MonoGame.Extended/SceneGraphs/SceneNode.cs, Source/MonoGame.Extended/Transform.cs
- Fix bug in `Transform2D` where local matrix wouldn't be updated if the parent's local matrix updated.
- Fix `Scale` and `Rotation` property in `Matrix2D`.
- Add `WorldPosition`, `WorldRotation`, and `WorldScale` to `Transform2D`.
- Update `SceneNode` to use `Transform2D` as base class.
- Update SceneGraph demo; works as expected.
=> SceneNode & Transform2D

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileSetTile.cs
Those changes make the "per tile ObjectGroups" available. They are used by Tiled for tile collision using Objects.
=> Objectgroups for Tiles!

Source/Demos/Demo.TiledMaps/Game1.cs, Source/MonoGame.Extended/FramesPerSecondCounter.cs, Source/MonoGame.Extended/FramesPerSecondCounterComponent.cs
-Update the logic based off [Shawn's blog](https://blogs.msdn.microsoft.com/shawnhar/2007/06/08/displaying-the-framerate/) so the frames per second is really the number of frames _per second_, not the game time budget of the frame.
-Removed averaging. It's not used in the TiledMaps.Demo and is a small waste of CPU time and memory resources.
-Update `FramesPerSecondCounterComponent`.
-Tested TiledMaps.Demo. Works correctly.
EDIT: From the comments section on Shawn's blog post
> > Surely 1 / gameTime.ElapsedRealTime.TotalSeconds 
> > will therefore give the current framerate.
> 
> That will tell you how long it was since the previous call to Update, but that is not the same thing as your framerate!
> a) If the game is dropping frames, Update will be called more frequently in order to catch …
=> fix FramesPerSecondCounter

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileSetTile.cs
So this time, everything is fixed and actually tested: The tilemap demo
works just fine (apart from Game.Exit() being obsolete). Those
objectgroups are now available in their respective TileSetTiles as seen
in this screenshot: http://screencast.com/t/YvdCmQoUcd
=> Objectgroups in Tiles (fixed)

Source/MonoGame.Extended.Tests/Shapes/RectangleFTests.cs, Source/MonoGame.Extended/TextureAtlases/TextureAtlas.cs
What the constructor does is take the `Dictionary<string, Rectangle>` of regions together with `Texture2D` and populates the `TextureAtlas.Regions` with them. Constructor is useful if the atlas regions are defined in the separate XML file which Content Pipeline deserializes into dictionary.
Also, I hope the documentation is... decent, at least, as I've done it by hand. If it's good enough, I might continue on with other classes.
=> Added a new constructor and documentation to TextureAtlas class

Source/Demos/Demo.BitmapFonts/Game1.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs
Added additional overloads to the BitmapFont DrawString methods to support the same functions the SpriteBatch.DrawString have. BitmapFont DrawString now supports scaling, orgins, SpriteEffects. Also updated the demo to showcase all of these.
=> New overloads for BitmapFont DrawString

Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj, Source/MonoGame.Extended.Tests/Primitives/BoundingBox2DTests.cs, Source/MonoGame.Extended.Tests/Primitives/Point2Tests.cs, Source/MonoGame.Extended.Tests/Primitives/Ray2DTests.cs, Source/MonoGame.Extended.Tests/Primitives/Segment2DTests.cs, Source/MonoGame.Extended.Tests/Primitives/Size2Tests.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj, Source/MonoGame.Extended/Primitives/BoundingBox2D.cs, Source/MonoGame.Extended/Primitives/Point2.cs, Source/MonoGame.Extended/Primitives/Ray2D.cs, Source/MonoGame.Extended/Primitives/RayHelper.cs, Source/MonoGame.Extended/Primitives/Segment2D.cs, Source/MonoGame.Extended/Primitives/Size2.cs
Some basic primitives. Includes full documentation along with the unit tests for, every, damn, method and operator.
Primitives: `Point2`, `Size2`, `Segment2D`, `Ray2D`, `BoundingBox2D`.
I added a `Point2` because [technically it is _not_ the same as a `Vector2`](http://math.stackexchange.com/questions/645672/what-is-the-difference-between-a-point-and-a-vector). However, I added all the operators to `Point2` which make sense, including translation by a displacement vector which I would expect would be used most commonly.
`Size2` might not be useful since we already have a `Size` and `SizeF`, but later I'm going to add a `Size3` which would have a base, width and height fields which would be used for a `BoundingBox3D` for example. I added `Size2` just to be consistent with naming. …
=> Some Basic Primitives.

Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs
Hey, here's a little fix for issue #188.
I think the actual scale, doing at an individual letter level, was not really useful, it's much more convenient to have a scale for the full sentence. This way we would require less bitmap fonts to write texts of multiple size in projects.
Here are some examples using the demo :
I think it should be a great temporary solution before finding one that would also correct the rotation issue, which I haven't investigated yet.
I've directly modified the existing draw, I don't really know if we need both solution for scaling.
=> Fixed scale for BitmapFont draws

Source/MonoGame.Extended/Maps/Tiled/TiledObject.cs
I removed the X and Y properties keeping Position property to make things less redundant.
I also added another constructor that takes a Vector2 position directly.
Reposted again because something weird was going on with the fork, so recreated a new one. Modified the code according to @craftworkgames's recommendations.
=> Removed the X and Y properties keeping Position

Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs
I have done what tests I can and it appears to work. May want to hold off on the PR until a few more people can confirm it works as expected for them.
Edge cases checked a bit too, ie one line strings in this version match one line strings from before so hopefully nothing would break anyone else using this to measure single lines.
=> BitmapFonts now returning a "rectangle" size.

Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs
This fixes #284 by setting baseVertex properly in call to DrawIndexedPrimitives when vertex buffer is larger than ushort.MaxValue
=> Fixed missing tiles when rendering large Tiled maps

Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs
The calculation of how many tiles were being drawn was being done (EffectPassesCount \* LayerCount \* TilesetCount) times each time the map was being drawn.  For small maps this wasn't a big deal but for larger maps such as the 500x500 untitled.tmx map storing the counts at the TiledTileLayer level took my FPS from ~37 to ~90 FPS.  Also tested against level01/02/03 and Platformer demo but those maps were too small to see any improvement.
=> Precalculate tilecount per tileset when TiledTileLayer is created

Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs, Source/MonoGame.Extended/Maps/Tiled/TiledRenderDetails.cs, Source/MonoGame.Extended/Maps/Tiled/TiledTileLayer.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj
One more performance optimization for Tiled map rendering (I don't think there's anymore low-hanging fruit in terms of performance).  I noticed that for any map (lets say 100x100 tiles for example) we were drawing 10,000 tiles for each tileset/layer combination even if the tile was blank.  Considering most layers beyond the "base" layer usually have more blank tiles than visible tiles, this is a huge waste.
By only drawing tiles for those that existed I was able to improve the FPS on my machine for untitled.tmx (500x500) from ~90 to ~1,100 FPS.  The vertices/indexes for DrawIndexedPrimatives are saved in a new class TiledRenderDetails on each layer at layer creation and fetched during TiledMap.Draw.
I've tested these changes on the Platformer and TiledTileMap demos.
=> Only draw tiles that actually exist for each tileset/layer combination

Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs
I'm not using the MonoGame content pipeline, so i need the contructor to be public to be able to manually load a BitmapFont from file
=> Made BitmapFont ctr public

Source/Demos/Demo.TiledMaps/Game1.cs, Source/MonoGame.Extended/Maps/Renderers/DynamicGroupRenderDetails.cs, Source/MonoGame.Extended/Maps/Renderers/FullMapRenderer.cs, Source/MonoGame.Extended/Maps/Renderers/GroupRenderDetails.cs, Source/MonoGame.Extended/Maps/Renderers/IMapRenderer.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj
I'd recommend to use the "very-large" demo map (you have to adjust the camera to look at 0/0 (I didn't want to change the lookAt value for all maps in the demo application).
Open for discussion:
* Only Tiles are animated. Are animated object and image layers are needed? 
* Is there a better way to get the camera viewport?
* Should we store the absolute tile position in each TiledTile? So we wouldn't need to create a new Rectangle for each tile in the "is in viewport"-check.
* I've moved the VBO and IBO construction into the GroupRenderDetails constructor because I think it's more appropriate there (it also allows to use SetVertices without recreating a new vbo in every call)
=> Implemented animated tiles

Source/MonoGame.Extended.Tests/Maps/Renderers/FullMapRendererTest.cs, Source/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj, Source/MonoGame.Extended.Tests/Shapes/EllipseFTest.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledObject.cs, Source/MonoGame.Extended/MonoGame.Extended.csproj, Source/MonoGame.Extended/Shapes/EllipseF.cs, Source/MonoGame.Extended/Shapes/PolylineF.cs
I noticed we're not parsing out TiledObjects into their associated Shapes and instead just storing the bounding rectangle.  I've updated the TiledMapReader and TiledObject to now store the shape for easy access.  This required creating 2 new shapes: EllipseF and PolylineF.  I realize that having both an EllipseF and CircleF is a little redundant but CircleF had a few methods I wasn't ready to implement on EllipseF.
=> Include IShapeF object as part of the TiledObject

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, Source/MonoGame.Extended/Maps/Renderers/FullMapRenderer.cs, Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs, Source/MonoGame.Extended/Maps/Tiled/TiledObject.cs
- Fixed calculation of x and y radius for ellipse
- Removed obsolete TiledObject.Points property
- Don't rebuild dynamic render details when no map is loaded
=> Fixed calculation of x and y radius for ellipse

Source/MonoGame.Extended.Tiled/Graphics/ITiledMapEffect.cs, Source/MonoGame.Extended.Tiled/Graphics/TiledMapDefaultEffect.cs, Source/MonoGame.Extended.Tiled/Graphics/TiledMapRenderer.cs, Source/MonoGame.Extended.Tiled/MonoGame.Extended.Tiled.csproj
Fixes #343 
Custom effects can be passed  to `Draw` overloads of `TiledMapRenderer`. Custom effects do however require to implement `ITiledMapEffect` to get and set the active texture and alpha transparency for a custom effect.
=> TiledMapRenderer allow custom effect

Source/Demos/Demo.Animations/Demo.Animations.csproj, Source/Demos/Demo.Batching/Demo.Batching.csproj, Source/Demos/Demo.BitmapFonts/Demo.BitmapFonts.csproj, Source/Demos/Demo.Camera/Demo.Camera.csproj, Source/Demos/Demo.EntityComponentSystem/Demo.EntityComponentSystem.csproj, Source/Demos/Demo.Gui/Demo.Gui.csproj, Source/Demos/Demo.InputListeners/Demo.InputListeners.csproj, Source/Demos/Demo.NuclexGui/Demo.NuclexGui.csproj, Source/Demos/Demo.Particles/Demo.Particles.csproj, Source/Demos/Demo.Platformer/Demo.Platformer.csproj, Source/Demos/Demo.SceneGraphs/Demo.SceneGraphs.csproj, Source/Demos/Demo.Screens/Demo.Screens.csproj, Source/Demos/Demo.SpaceGame/Demo.SpaceGame.csproj, Source/Demos/Demo.SpriteSheetAnimations/Demo.SpriteSheetAnimatons.csproj, Source/Demos/Demo.Sprites/Demo.Sprites.csproj, Source/Demos/Demo.TiledMaps/Demo.TiledMaps.csproj, Source/Demos/Demo.ViewportAdapters/Demo.ViewportAdapters.csproj, Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj, Source/MonoGame.Extended.Content.Pipeline/packages.config
Stuff done:
- Use MG.Content.Pipeline.Portable for MG.Extended.Content.Pipeline project
- Fix links to native libraries so they point to a location that works with both Windows and Linux
=> Fix project files so they can build from Linux

Source/MonoGame.Extended/TextureAtlases/TextureAtlas.cs
Also added method that checks whether a region exists in the texture atlas.
I develop UI library for the MonoGame: https://github.com/rds1983/Myra/
Our projects share a lot of common(bitmap fonts, texture atlases, etc). Therefore I decided to move Myra on top of MonoGame.Extended. It would require some adjustments of the MonoGame.Extended. That PR is one of it. I hope it gets through.
=> Added ability to create nine patch regions in a texture atlas.

Source/Demos/Demo.StarWarrior/GameMain.cs, Source/Demos/Demo.StarWarrior/Systems/PlayerShipControlSystem.cs, Source/MonoGame.Extended.Content.Pipeline/BitmapFonts/BitmapFontWriter.cs, Source/MonoGame.Extended.Graphics/Batcher2D.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontReader.cs, Source/MonoGame.Extended/BitmapFonts/BitmapFontRegion.cs
Fixes #371 
Following our discussion I've added static property UseKernings(initially set to false) to Bitmap that controls whether kernings are applied during the rendering.
Also I've slightly updated the StarWarrior demo. Now you can turn on/off that property by pressing 'K' key. The difference is visible only in Debug mode(where additional text is drawn).
=> Added kernings support to the BitmapFont.

Source/MonoGame.Extended.Entities/Entities/TransformComponent2D.cs, Source/MonoGame.Extended/Transform.cs
Fixes issues discussed in forum thread:
http://community.monogame.net/t/entities-nested-using-transformcomponent2d-parent/9084
Correctly calculates the WorldMatrix for Transform and TransformComponent2D that have parents (any depth) who are rotated and/or scaled.
=> Fix nested transform WorldMatrix calculation

Source/MonoGame.Extended/Content/ContentReaderExtensions.cs
This scratch buffer is `internal`, it has a 1mb limit, and it's unused.
I think if devs want a scratch buffer, maybe there should be a `ScratchBuffer` class with a static internal byte array.
Recompiled whole solution successfully with it removed.
=> [Content] removing unused ScratchBuffer

Source/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/MonoGame.Extended.Content.Pipeline.Tests.Tiled.csproj, Source/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/packages.config, Source/Tests/MonoGame.Extended.Content.Pipeline.Tests/MonoGame.Extended.Content.Pipeline.Tests.csproj, Source/Tests/MonoGame.Extended.Content.Pipeline.Tests/packages.config, Source/Tests/MonoGame.Extended.Gui.Tests/MonoGame.Extended.Gui.Tests.csproj, Source/Tests/MonoGame.Extended.Gui.Tests/packages.config, Source/Tests/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj, Source/Tests/MonoGame.Extended.Tests/packages.config, Source/Tests/MonoGame.Extended.Tiled.Tests/MonoGame.Extended.Tiled.Tests.csproj, Source/Tests/MonoGame.Extended.Tiled.Tests/packages.config
Without this change, the tests fail in Visual Studio.  Because they are trying to use functionality that is missing in the Portable version of MonoGame. 
For example `MathHelper.Clamp` always returns `0f` in the portable version, because it has no implementation.
=> Tests moved MonoGame from Portable to WindowsDX

Docs/Community-and-Support.md
I forgot myself, so I had to look it up on the mkdocs site.  I think it's worth putting in here just to remind that you run it from the MonoGame.Extended folder, and that all pages must be in `mkdocs.yml`
=> Added some command lines to run mkdocs

Source/MonoGame.Extended/HslColor.cs, Source/Tests/MonoGame.Extended.Tests/Particles/ColourTests.cs
The Hue value was being calculated as a value between 0 and 1. Now it is calculated to be between 0 and 360.
=> Change FromRgb() method to create the Hue value correctly

Source/MonoGame.Extended/Sprites/SpriteExtensions.cs
Sprite's parent transform is ignored when drawing via SpriteBatch extension method.
=> Use sprite WorldMatrix for drawing

Source/MonoGame.Extended.NuclexGui/Visuals/Flat/FlatGuiVisualizer.cs
With this Nuclex GUI can use visualizers, defined in an application. This allows people to develop custom controls, without compiling MG.EX (like from a nugget package).
One just has to add the binary, containing the visualizer, before the call to GuiManager.Initialize.
=> Added support for external renderers.

Source/MonoGame.Extended.Entities/Entity.cs
The reset method was not clearing the name field.  When a "new" entity is retrieved from the pool, it could have the old entity's name.
=> Modified Entity's Reset method to clear _name field

Source/Demos/Demo.Features/Content/adventure-gui-skin.json, Source/Demos/Demo.Features/GameMain.cs, Source/Demos/Demo.Features/Screens/SelectDemoScreen.cs, Source/MonoGame.Extended.Gui/Controls/GuiButton.cs, Source/MonoGame.Extended.Gui/Controls/GuiControl.cs, Source/MonoGame.Extended.Gui/GuiElement.cs, Source/Tests/MonoGame.Extended.Gui.Tests/Controls/GuiButtonTests.cs
Allows the option to use images on buttons instead of only text:
=> [GUI] Added support for icons on buttons

Source/MonoGame.Extended.Entities/Entity.cs, Source/MonoGame.Extended/Collections/ObjectPool.cs
There were several issues with enumeration of the ObjectPool.
1. _headNode was never getting assigned
2. _tailNode's NextNode field was being set to itself causing infinite loop during enumeration
3. The GetEnumerator method was not including the _headNode in the results.  It was starting with the second node in the pool.
=> ObjectPool Enumeration Bug

Source/Demos/Demo.SpaceGame/Entities/Spaceship.cs, Source/Demos/Demo.SpaceGame/Game1.cs, Source/Demos/Demo.StarWarrior/packages.config
I was learning how to use MonoGame.Extended from the demos and noticed that the aim for SpaceGame was off. I went ahead and fixed it for myself.
It looked like the person who wrote had their axis backwards, since in MonoGame increasing y value means the sprite will move down the screen.
I wasn't sure if this was fixed in 2.0, as when I downloaded 2.0, this demo wasn't working.
Thanks
=> Fix Demo.SpaceGame aiming and spaceship control

Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs
Kerning value 'amount' wasn't being applied to the '_currentGlyph.Position.X' in either MoveNext() methods, only '_positionDelta.X'. Both are needed for proper positioning.
=> Apply kerning to the current glyph.

Source/MonoGame.Extended.NuclexGui/GuiScreen.cs
Screen Desktop defaulted to being width of 1, and height of 1, instead of width of 100%, and height of 100%
=> Bug - Fixed default bounds of Screen desktop

Source/MonoGame.Extended.NuclexGui/Controls/Desktop/GuiResizableControl.cs, Source/MonoGame.Extended.NuclexGui/Controls/Desktop/GuiSliderControl.cs, Source/MonoGame.Extended.NuclexGui/Controls/Desktop/GuiWindowControl.cs, Source/MonoGame.Extended.NuclexGui/Controls/GuiControl.cs, Source/MonoGame.Extended.NuclexGui/Controls/GuiControlInput.cs, Source/MonoGame.Extended.NuclexGui/Controls/GuiPressableControl.cs, Source/MonoGame.Extended.NuclexGui/MonoGame.Extended.NuclexGui.csproj
Implemented GuiResizableControl, and made GuiWindowControl inherit from it.
GuiResizableControl is a control that can be resized.
GuiResizableControl calls SetCursorForResize(_resizingSides), which can be overridden to provide platform-specific mouse cursor implementation depending on where on the edge of the control your mouse is.
=> Implemented GuiResizableControl

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapLayerModelContent.cs, Source/MonoGame.Extended.Graphics/Geometry/GeometryBuilder2D.cs, Source/MonoGame.Extended.Tiled/TiledMapTilesetTileAnimationFrame.cs
Fixes rendering issue from #476. `0.5f` was added to the texture rendering logic to prevent tile bleeding, but causes the tile to be rendered 1/2 pixel less in width and height, then stretched to the full size of the tile. The other bleeding issues I found in that issue appear to be unrelated.
=> Fix Texture Alignment

Source/MonoGame.Extended.Gui/GuiSystem.cs
The background of the dialogues was being drawn below the controls of other dialogs.
Before the PR:
After:
=> Fix GUI children drawing

Source/MonoGame.Extended/TextureAtlases/TextureAtlas.cs
When removing a `TextureRegion2D` from a `TextureAtlas`, referencing the `TextureRegion2D`s by index works, but referencing by name points to the old index. The only way I could think of making the current code work would be to rebuild the `Dictionary<string, int>` every time, or atleast the parts which are affected by the removal. Instead of rebuilding the internal `Dictionary<string, int> _regionMap` every time an entry is removed, I changed the signature to `Dictionary<string, TextureRegion2D>`. This eliminates the need to translate the name into a `List<TextureRegion2D>` index in the first place.
What do you guys think?
=> Remove bug in TextureAtlas.RemoveRegion

Source/MonoGame.Extended.Graphics/Geometry/GeometryBuilder2D.cs, Source/MonoGame.Extended.Tiled/TiledMapTilesetTileAnimationFrame.cs
When I released #480 to fix some texture alignment issues, I failed to check the variable types for the math being done. With my original fix by removing the `+ 0.5f` overdraw, the math changed from `float` division to `int` division. I'm now recasting for `float` division as it should be!
My bad!!
=> Texture bug fix

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImageContent.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapProcessor.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapTilesetProcessor.cs
Pass the transparent color provided by the .TMX or .TSX file to the Texture processor for custom transparency.
=> Build Textures With Prefered Transparent Color

Source/Demos/Features/Demos/CollisionDemo.cs, Source/MonoGame.Extended.Collisions/QuadTree/CollisionComponent.cs
There was a bug with how the penetration vector was calculated between circles and rectangles. This PR fixes the bug and adds a controllable ball to the collision demo better allowing this behavior to be tested.
=> Circle Rectangle penetration vector fix

Source/MonoGame.Extended.Gui/Controls/TextBox.cs, Source/MonoGame.Extended.Gui/GuiSystem.cs
When I want to create an instantiated control by means of reflection, it has an error and requires a constructor with no arguments. So I want to fix it.
Another one is to change the readability of updatecontrol to public, because when I want to use this library, there is a conflict, I have to manually update the state of the control. I can't update the state with guisystem.update. Because it will happen to find an instance of TouchPad.
https://github.com/MarcStan/MonoGame.Framework.WpfInterop/issues/10
=> fix reflection bug

Source/MonoGame.Extended/Screens/ScreenManager.cs
It seems the two IF conditions is not needed.
When using the function of ScreenManager.LoadScreen(),  the isLoaded variable has already been setted to true.
=> Remove isLoaded when load screen

Source/MonoGame.Extended.Particles/ParticleEmitter.cs, Source/MonoGame.Extended.Particles/ParticleReleaseParameters.cs
Basically added a ScaleX and ScaleY, and a MaintainAspectRatio switch to ParticleReleaseParametes. Pretty simple change that adds some additional functionality to the particle system that shouldn't have any performance impacts.
Example:
```csharp
_particleEffect = new ParticleEffect
{
Emitters = new List<ParticleEmitter>
{
new ParticleEmitter(textureRegion, 500, TimeSpan.FromSeconds(2.5),
Profile.Ring(150f, Profile.CircleRadiation.In))
{
Parameters = new ParticleReleaseParameters
{
Speed = new Range<float>(0f, 50f),
Quantity = 1,
MaintainAspectRatioOnScale = false,
ScaleX = new Range<float>(10f, 60f),
ScaleY = new Range<float>(10f, 50f),
Rotation = 0
}
}
}
};
````
(Video:https://i.imgur.com/Aqx0Xzy.gifv)
=> Scale Particles without Maintaining Aspect Ratio

Source/MonoGame.Extended.Entities/World.cs
Calling world dispose, _drawSystems and _updateSystems should be cleaned up I think.
If it is not, calling world.Dispose() doesn't not effetctively clean up the world.
In my case I have a TiledMapRenderer used from a RenderSystem to draw the map. If I dispose the world, the render system should be garbage collected. If it is not, the tiledMapRenderer still draws the map because the RenderSystem still exists.
If there is a better way to do this please let me know.
=> ensure systems cleanup on world dispose

Source/MonoGame.Extended.Tiled/TiledMap.cs
This PR adds checks for an existing layer by name before adding new layer for a TiledMap (see #617) If layer name already exists, a descriptive exception is thrown instead of the generic ArgumentException.
=> Check for existing layer name

Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapImporter.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapObjectTemplateImporter.cs, Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapTilesetImporter.cs
I was having an issue loading Tiled maps, since in some cases the path to the asset contained \\ and / along the same path.  When debugging the pipeline writers, I would see things like this for the path:
"C:\\Users\\Cory\\source\\repos\\MonoGame\\Tools\\Pipeline\\Content/CollisionTileSet.tsx"
Using Path.Combine instead kept the slashes consistent and fixed the issue.
I looked for other placed in MonoGame.Extended with this same pattern and replaced them with Path.Combine.
=> Fixed pathing issues creating problems loading Tiled assets

Source/Demos/Tutorials/Demos/CollisionDemo.cs, Source/Demos/Tutorials/GameMain.cs, Source/Demos/Tutorials/Tutorials.csproj, Source/MonoGame.Extended.Collisions/QuadTree/CollisionComponent.cs, Source/MonoGame.Extended.Collisions/QuadTree/QuadTree.cs, Source/MonoGame.Extended.Collisions/QuadTree/QuadTreeData.cs, Source/Tests/MonoGame.Extended.Collisions.Tests/QuadTreeTests.cs
Performance Improvements
- `QuadtreeData `now keeps track of its parents. This makes removing it from a `Quadtree `a lot faster.
- `Reset()` is removed and Dirty `QuadtreeData `is now tracked and reset inside the functions that use the Dirty flag.
- `Quadtree.Contents` is now a `HashSet`. This makes removing faster
- `Shake()` now only gets called at the end of update and explicit remove
I tested this with 1000 colliders and the fps went from ~1 to 60
=> Improved collision performance and Re-added collision demo

Source/MonoGame.Extended/Screens/Transitions/FadeTransition.cs
The FadeTransition had visual glitches when combined with a BoxingViewportAdapter. This happened because the viewport's offset was applied twice.
=> Fix: FadeTransition glitch

src/dotnet/MonoGame.Extended.Particles/ParticleEmitter.cs
Right now, every `ParticleEmitter` generates the same random spread of particles. This isn't so noticeable with lots of particles but with a low number (e.g. 5 particles in a spurt) it's very noticeable.
This is because the default `FastRandom` constructor initialises with a seed of `1`.
This simply initialises the `FastRandom` with a random seed used by generating a new guid. We must use `Math.Abs` because FastRandom only accepts positive integers for the seed.
=> Fix ParticleEmitters always using same random seed

src/dotnet/MonoGame.Extended.Tiled/Serialization/TiledMapImageContent.cs
`Color.TransparentBlack` has been removed in Monogame.
https://github.com/MonoGame/MonoGame/commit/c6d916d6983526900869d5e2f189471224f06c14
When using a development version of mgcb-editor (3.8.1.1983-develop) I was unable to build a .tmx file because of the usage of `Color.TransparentBlack` in `TiledMapImageContent.cs`.
I have replaced it with `Color.Tranparent` which is the replacement and has the same value.
=> Replace Color.TransparentBlack with Color.Transparent

src/cs/MonoGame.Extended.Particles/ParticleEffect.cs, src/cs/MonoGame.Extended.Particles/ParticleEmitter.cs
Hi! I needed the ability to define the layerdepth also for autotriggered particleeffects so I've added this little feature, it was just a few lines and seems to work very well.
This is the first time I contribute something to any OS project, so please be lenient if I did something wrong.
=> add ability to configure layerdepth for autotriggered particleeffects

src/cs/MonoGame.Extended.Tiled/TiledMapTileLayer.cs
when calling `TryGetTile` on `TileMapTileLayer` and using a `y`  coordinate greater then the height the method returns `false`.
Doing the same with `x` while `y` is not at maximum will return `true`.
This will check the `x` used and returns false if it is over the width.
=> TryGetTile no longer returns a value if width is outside the map

.github/workflows/build-test-deploy.yml, src/cs/MonoGame.Extended.Animations/MonoGame.Extended.Animations.csproj, src/cs/MonoGame.Extended.Collisions/MonoGame.Extended.Collisions.csproj, src/cs/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj, src/cs/MonoGame.Extended.Entities/MonoGame.Extended.Entities.csproj, src/cs/MonoGame.Extended.Graphics/MonoGame.Extended.Graphics.csproj, src/cs/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj, src/cs/MonoGame.Extended.Input/MonoGame.Extended.Input.csproj, src/cs/MonoGame.Extended.Particles/MonoGame.Extended.Particles.csproj, src/cs/MonoGame.Extended.Tiled/MonoGame.Extended.Tiled.csproj, src/cs/MonoGame.Extended.Tweening/MonoGame.Extended.Tweening.csproj, src/cs/MonoGame.Extended/MonoGame.Extended.csproj, src/cs/Tests/MonoGame.Extended.Collisions.Tests/MonoGame.Extended.Collisions.Tests.csproj, src/cs/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/MonoGame.Extended.Content.Pipeline.Tests.Tiled.csproj, src/cs/Tests/MonoGame.Extended.Content.Pipeline.Tests/MonoGame.Extended.Content.Pipeline.Tests.csproj, src/cs/Tests/MonoGame.Extended.Entities.Tests/MonoGame.Extended.Entities.Tests.csproj, src/cs/Tests/MonoGame.Extended.Gui.Tests/MonoGame.Extended.Gui.Tests.csproj, src/cs/Tests/MonoGame.Extended.Tests/MonoGame.Extended.Tests.csproj, src/cs/Tests/MonoGame.Extended.Tiled.Tests/MonoGame.Extended.Tiled.Tests.csproj
MG: 3.8  -> 3.8.1
dotnet:
+ coreapp3.1 -> net6
+ netstandard2.0 -> net6
=> Updated MonoGame Versions

src/cs/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapProcessor.cs, src/cs/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapTilesetWriter.cs, src/cs/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, src/cs/MonoGame.Extended.Tiled/Serialization/TiledMapObjectContent.cs, src/cs/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/TestData/test-object-layer.tmx, src/cs/Tests/MonoGame.Extended.Content.Pipeline.Tests.Tiled/TiledMapImporterProcessorTests.cs
As of Tiled version 1.9.0 the `type` attribute of objects has been replaced by the `class` attribute, as is reflected by the documentation [here](https://doc.mapeditor.org/en/stable/manual/custom-properties/#custom-classes). This change prefers the `class` attribute and falls back to the `type` attribute. For compatibility reasons I haven't updated the name of the `Type` field in [`TiledMapObject`](https://github.com/craftworkgames/MonoGame.Extended/blob/9a539d0517b9299a3e381547d47c6a2771f34bbe/src/cs/MonoGame.Extended.Tiled/TiledMapObject.cs#L22).
=> Tiled: Support class attribute as alias for object types

.gitignore, src/cs/MonoGame.Extended/Math/PrimitivesHelper.cs, src/cs/Tests/MonoGame.Extended.Tests/Primitives/RectangleFTests.cs
=> Fix rectangle transform

src/cs/MonoGame.Extended/TextureAtlases/TextureAtlasJsonConverter.cs
If I use AnimationSprite on Android, App happened exception 'TitleContainer.OpenStream requires a relative path' at TextureAtlasJsonConverter.
MonoGame's content loader need relative path on Android.
This fix is load content by relative path if happened exception.
=> Fix crash at loading AnimationSprite on Android.

src/cs/MonoGame.Extended.Input/MouseButton.cs
Add power of two values to `MouseButton` so `MouseButton.HasFlags` can be used.
=> Add power of two values to MouseButton

src/cs/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs, src/cs/MonoGame.Extended.Tiled/Renderers/TiledMapRenderer.cs, src/cs/MonoGame.Extended.Tiled/Serialization/TiledMapLayerContent.cs, src/cs/MonoGame.Extended.Tiled/TiledMapGroupLayer.cs, src/cs/MonoGame.Extended.Tiled/TiledMapImageLayer.cs, src/cs/MonoGame.Extended.Tiled/TiledMapLayer.cs, src/cs/MonoGame.Extended.Tiled/TiledMapObjectLayer.cs, src/cs/MonoGame.Extended.Tiled/TiledMapReader.cs, src/cs/MonoGame.Extended.Tiled/TiledMapTileLayer.cs
Add implements of parallaxFactor for Tiled Map.
1. Reading parallaxFactor from Tiled files.
2. Writing in XNB.
3. Reading from XNB in layers objects.
4. Use parallaxFactor if not One when render Tiled Map.
This should resolve #800
=> Tiled parallax factor

src/cs/MonoGame.Extended.Collisions/QuadTree/CollisionComponent.cs, src/cs/MonoGame.Extended.Collisions/QuadTree/QuadTree.cs, src/cs/MonoGame.Extended.Collisions/QuadTree/QuadTreeData.cs, src/cs/Tests/MonoGame.Extended.Collisions.Tests/CollisionComponentTests.cs
Resolve #796 
Potentially resolve #591 
I changed the algorithm, so that the **actual** bounds are always used. I don't know if this will cause any unwanted side-effects.
A couple of unit tests were added to prove the case.
=> OnCollision are called even after objects involved are moved and not intersecting

src/cs/MonoGame.Extended/Sprites/SpriteSheetAnimation.cs, src/cs/Tests/MonoGame.Extended.Tests/Sprites/SpriteSheetAnimationTests.cs
- Fix looping animations incorrectly completing when an update contains a large elapsed time.
- Ping pong waits until frame delay is complete on re-entry of the first frame before firing Complete rather than firing Complete immediately upon entering the frame.  This makes it consistent with a non ping pong animation which waits for the frame delay of the last frame before it fires Complete. 
- Ping Pong now finishes on the first frame rather than potentially finishing on a different frame if the elapsed time since last update was larger than the time remaining for the animation to become complete. 
- Add unit tests for SpriteSheetAnimation.
=> Fix bugs in SpriteSheetAnimation

src/cs/MonoGame.Extended/Collections/Bag.cs, src/cs/Tests/MonoGame.Extended.Tests/Collections/BagTests.cs
The documentation of Entities recommends iteration through a `Bag<int>` of entities with `foreach`. However, due to `Bag<T>` not providing a duck-typed enumerator for `foreach`, this causes memory allocation. If a system processes a large number of entities  (let's say 100k, which is reasonable for an ECS framework) this will cause 100k `BagEnumerator` allocations per frame (!) due to the boxing conversion when the internal `BagEnumerator` is converted to `IEnumerator`.
More information about this problem can be found here: https://nede.dev/blog/preventing-unnecessary-allocation-in-net-collections
This PR fixes this by simply adding a duck-typed `GetEnumerator()` method, and making `BagEnumerator` public. It also adds a unit test to prevent future issues while using `foreach`.
=> Fix Bag<T> allocation during foreach iteration

.github/workflows/build-test-deploy.yml, .gitignore, Directory.Build.targets, build/Build.csproj, build/BuildContext.cs, build/BuildTask.cs, build/DeployToGithubTask.cs, build/DeployToMyGetTask.cs, build/DeployToNuGetTask.cs, build/PackageTask.cs, build/Program.cs, build/RestoreTask.cs, build/TestTask.cs, src/cs/MonoGame.Extended.Animations/MonoGame.Extended.Animations.csproj, src/cs/MonoGame.Extended.Collisions/MonoGame.Extended.Collisions.csproj, src/cs/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj, src/cs/MonoGame.Extended.Entities/MonoGame.Extended.Entities.csproj, src/cs/MonoGame.Extended.Graphics/MonoGame.Extended.Graphics.csproj, src/cs/MonoGame.Extended.Gui/MonoGame.Extended.Gui.csproj, src/cs/MonoGame.Extended.Input/MonoGame.Extended.Input.csproj, src/cs/MonoGame.Extended.Particles/MonoGame.Extended.Particles.csproj, src/cs/MonoGame.Extended.Tiled/MonoGame.Extended.Tiled.csproj, src/cs/MonoGame.Extended.Tweening/MonoGame.Extended.Tweening.csproj, src/cs/MonoGame.Extended/MonoGame.Extended.csproj, src/cs/Tests/MonoGame.Extended.Tests/Collections/BagTests.cs
After speaking with Lithium earlier, I have created this PR to update the GitHub Actions workflow for automating the NuGet pacakge releases both for the official NuGet source and Lithium's MyGet source.
This PR updates the GitHub Action to automate the build, test, package, and NuGet deployment.  The build, test, and package steps have been moved into a Cake Frosting project which is called from the GitHub Action.
Note that the package task does not execute unless a push is made into the `develop` branch.  This is so packaging is not run during a PR, and only runs when a PR is merged into `develop` or a direct push is made to `develop`
The GitHub Action was also updated to automate NuGet package deployment to the following locations
- GitHub Packages within this repository
- Lithium's …
=> Update GitHub Workflow to Automate Build, Test, and Package Deployment

src/cs/MonoGame.Extended.Input/KeyboardStateExtended.cs
`WasAnyKeyJustDown()` called a MonoGame method that allocated, when a better one was available.
Additionally, `GetPressedKeys(Keys[] keys)` overload to allow the caller to cache was present on `KeyboardState`, but missing on `KeyboardStateExtended`. 
Fixed both things.
=> Decrease allocation overhead on KeyboardStateExtended

src/cs/MonoGame.Extended/Math/ShapeF.cs
This PR resolves the infinite recursion bug in `Shape.Intersects(this IShapeF, IShapeF)` when both parameters are of type `RectangleF`.
- Closes #850 
- #849
=> Resolves Infinite Recursion with Shape.Intersects(this IShapeF, IShapeF)

build/Program.cs
Disabling the deploy to Lithium's MyGet feed.  The MyGet feed is configured to not allow pushes with versions that aren't strictly [Major].[Minor].[Patch].
- #830
=> Removing MyGet Feed Deploy

.github/FUNDING.yml
This removes the patreon link from the funding section and adds aristurtledev as a sponserable maintainer
=> Removed patreon added aristurtledev

tests/MonoGame.Extended.Tests/Shapes/PolygonFTests.cs, tests/MonoGame.Extended.Tests/Shapes/PolygonTests.cs
In order to ensure consistency in behavior with MonoGame and MonoGame.Extended, a new test was added to the `Polygon` tests that ensures a point that exists on an edge of a polygon is not "contained" within the polygon.
- https://github.com/craftworkgames/MonoGame.Extended/issues/214
=> Add Edge Test for `Polygon.Contains`

source/MonoGame.Extended.Collisions/SpatialHash.cs, source/MonoGame.Extended.Gui/Controls/UniformGrid.cs, source/MonoGame.Extended.Gui/Screen.cs, source/MonoGame.Extended.Tiled/Serialization/TiledMapLayerModelContent.cs, source/MonoGame.Extended.Tiled/TiledMapEllipseObject.cs, source/MonoGame.Extended.Tiled/TiledMapObject.cs, source/MonoGame.Extended.Tiled/TiledMapPolygonObject.cs, source/MonoGame.Extended.Tiled/TiledMapPolylineObject.cs, source/MonoGame.Extended.Tiled/TiledMapReader.cs, source/MonoGame.Extended.Tiled/TiledMapRectangleObject.cs, source/MonoGame.Extended.Tiled/TiledMapTileObject.cs, source/MonoGame.Extended.Tiled/TiledMapTilesetReader.cs, source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, source/MonoGame.Extended/ISizable.cs, source/MonoGame.Extended/Math/BoundingRectangle.cs, source/MonoGame.Extended/Math/OrientedRectangle.cs, source/MonoGame.Extended/Math/Point2.cs, source/MonoGame.Extended/Math/RectangleF.cs, source/MonoGame.Extended/Math/ShapeExtensions.cs, source/MonoGame.Extended/Math/Size.cs, source/MonoGame.Extended/Math/SizeF.cs, source/MonoGame.Extended/Math/Vector2Extensions.cs, source/MonoGame.Extended/Serialization/Size2JsonConverter.cs, source/MonoGame.Extended/TextureAtlases/TextureRegion2D.cs, tests/MonoGame.Extended.Collisions.Tests/CollisionComponentTests.cs, tests/MonoGame.Extended.Collisions.Tests/SpatialHashTests.cs, tests/MonoGame.Extended.Tests/Primitives/OrientedRectangleTests.cs, tests/MonoGame.Extended.Tests/Primitives/RectangleFTests.cs, tests/MonoGame.Extended.Tests/Primitives/ShapeTests.cs
Renamed`Size2` to `SizeF` to better define what it's behavior is and to align the naming convention with other types like `RectangleF`
- https://github.com/craftworkgames/MonoGame.Extended/issues/538
=> Rename `Size2` to `SizeF`

tests/MonoGame.Extended.Tests/BitmapFonts/BitmapFontTests.cs
This PR adds a unit test for `BitmapFont.MeasureString` to ensure that it accounts for the trailing space at the end of a string.  
Reference:
- https://github.com/craftworkgames/MonoGame.Extended/issues/695
=> Unit Test `BitmapFont.MeasureString` With Trailing Space

tests/MonoGame.Extended.Tests/Content/ContentReaderExtensionsTests.cs
Unit test added to confirm results of `ContentReaderExtensions.GetRelativeAssetName`
- https://github.com/craftworkgames/MonoGame.Extended/issues/633
=> Add unit test for `ContentReaderExtensions.GetRelativeAssetName`

source/MonoGame.Extended.Particles/ParticleBuffer.cs, source/MonoGame.Extended.Particles/ParticleEffect.cs, source/MonoGame.Extended.Particles/ParticleEmitter.cs, source/MonoGame.Extended.Particles/ParticleExtensions.cs
This PR implements the standard `IDisposable` pattern for `ParticleEffect`, `ParticleEmitter`, and `ParticleBuffer`.  
- https://github.com/craftworkgames/MonoGame.Extended/issues/745
=> Implement Standard IDispose Pattern For Particles

source/MonoGame.Extended/Math/OrientedRectangle.cs, source/MonoGame.Extended/MonoGame.Extended.csproj
- remove unused SharpDX using
introduces in https://github.com/craftworkgames/MonoGame.Extended/pull/840
- remove Content.Pipeline reference from the core library
introduced in https://github.com/craftworkgames/MonoGame.Extended/pull/692
=> Remove unnecessary dependencies to SharpDX and Content.Pipeline from the core library

source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj, source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.targets
This PR updates the `MonoGame.Extended.Content.Pipeline` NuGet to now include a `.targets` file. The target is set to run before the `RunContentBuilder` task from MonoGame and also before the generic `BeforeBuild` task as a fallback.  The task will copy the dlls that users need to reference from the NuGet package installation directory to the `/Content/refrences` directory in the project root.
This is implemented as a QoL update to make it easier to add the dll references needed without having to (1) create a nuget.config or (2) go hunting the dll down in global nuget cache directory.
=> Copy Reference DLLs from NuGet Automatically

source/MonoGame.Extended.Entities/ComponentManager.cs, tests/MonoGame.Extended.Entities.Tests/ComponentManagerTests.cs
Updated `ComponentManager` to implement `IEnumerable<ComponentMapper>` (#823)
- Updated `IComponentMapperService` and `ComponentManager` to implement `IEnumerable<ComponentMapper>`
- Added indexer `this[Type type]` to `ComponentManager` to provide the commonly used feature of enumerable/collection types
- Added related unit tests to `MonoGame.Extended.Entities.Tests.ComponentManagerTests`
=> Updated ComponentManager to implement IEnumerable<ComponentMapper> (#823)

source/MonoGame.Extended.Tiled/TiledMapProperties.cs, tests/MonoGame.Extended.Tiled.Tests/TileMapPropertiesTest.cs
This resolves an issue when, given a key that doesn't exist, the `TledMapProperties.TryGetValue` method would throw a `NullReferenceException`.
- https://github.com/craftworkgames/MonoGame.Extended/issues/901
=> Resolves NullReferenceException When Getting Invalid Key From TiledMapProperties

source/MonoGame.Extended/Collections/IPoolable.cs, source/MonoGame.Extended/Collections/ObjectPool.cs, tests/MonoGame.Extended.Tests/Collections/ObjectPoolTests.cs
Fix `NullReferenceException` in `ObjectPool` when reusing all returned items
The `ObjectPool`'s `Use()` method was throwing a `NullReferenceException` when all items had been returned to the pool and `New()` was called again. This was due to `_tailNode` being null in this scenario.
Added a null check for `_tailNode` in Use() method to properly reinitialize the linked list structure when the pool has been emptied and refilled.
- https://github.com/craftworkgames/MonoGame.Extended/issues/471
=> Fix `NullReferenceException` in `ObjectPool` when reusing all returned items

source/MonoGame.Extended/Camera.cs, source/MonoGame.Extended/OrthographicCamera.cs
This is a simple and unobtrusive addition to the Camera & OrthographicCamera classes that adds a pitch variable and implementation. The reason this is needed is because it allows the camera to better create a faux-3D or 2.5D perspective that can be rotated, zoomed, and pitched, as if it were a true 3D camera, while still maintaining that it is fundamentally 2D. The inclusion of this addition does not alter any existing functionality nor would it affect existing projects already using the OrthographicCamera class.
=> Add pitch support to Camera & OrthographicCamera

source/MonoGame.Extended.Content.Pipeline/BitmapFonts/BitmapFontImporter.cs, source/MonoGame.Extended.Content.Pipeline/BitmapFonts/BitmapFontProcessor.cs, source/MonoGame.Extended/Content/ContentReaders/BitmapFontContentReader.cs, source/MonoGame.Extended/Input/KeyboardExtended.cs, source/MonoGame.Extended/Input/KeyboardStateExtended.cs, source/MonoGame.Extended/Input/MouseExtended.cs, source/MonoGame.Extended/Input/MouseStateExtended.cs
=> Various fixes for the version 4 initial release

source/MonoGame.Extended/ColorExtensions.cs
By default, you can create a `Color` value using a packed `uint` value that is in the RGBA format where R is the least significant byte (LSB).  This can be awkward when you have a HTML styled hex color value such as `#112233` and you want to use that as the packed `uint` value, you have to reverse it for MonoGame by doing `new Color(0xFF332211);` so that R is the LSB
This PR adds a new method to `ColorExtension` that takes a packed `uint` value that is in ABGR format where A is the LSB and creates a `Color` value from it.  So you can use HTMl styled hex color values such as `#112233` and write it naturally by doing `ColorExtensions.FromAbgr(0x112233FF);`
This was added after a conversation in the MonoGame discord with Ritchie where they expressed the annoyance with not being able to do …
=> Added FromAbgr method

source/MonoGame.Extended/Particles/Modifiers/VortexModifier.cs
Implements the calculation from the Mercury Particle Engine that takes into account the `MaxSpeed` property.
- Closes #698
=> Use MaxSpeed when calculating speedGain

source/MonoGame.Extended/Math/PrimitivesHelper.cs
This resolves an issue where the `rayNearDistance` and `rayFarDistance` were not being swapped properly.
- Closes #726
=> Correctly swap rayNear and rayFar distance

source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, source/MonoGame.Extended/Content/BitmapFonts/BitmapFontFileReader.cs, source/MonoGame.Extended/Math/PrimitivesHelper.cs
The `bmfFile.Path` value was never set causing a `ArgumentNullException` to occur when building the path to the texure files for the bitmap font.
- Closes #923
=> Resolves `ArgmentNulLException` When Loading `BitmapFont` From Disk.

source/MonoGame.Extended/ColorExtensions.cs
Thanks @nkast 
from nkast
> Color in fna doesnt have a constructor that takes a packed uint value, actually it's private
> https://github.com/FNA-XNA/FNA/blob/31dab885817ddaece9758f480027373f0ad74bea/src/Color.cs#L1668
> There is a property PackedValue, (that implements the  IPackedVector<uint> interface.)
=> fix color extension bug

CHANGELOG.md, Directory.Build.props, README.md, benchmarks/Directory.Build.props, source/Directory.Build.props, source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj, source/MonoGame.Extended/.config/dotnet-tools.json, source/MonoGame.Extended/Math/Vector2Extensions.cs, tests/Directory.Build.props, tests/MonoGame.Extended.Content.Pipeline.Tests/MonoGame.Extended.Content.Pipeline.Tests.csproj, tests/MonoGame.Extended.Tests/Vector2ExtensionsTests.cs
This PR is to update MonoGame Extended for the new release of MonoGame 3.8.2.1105.
=> Update for Monogame 3.8.2.1105

source/MonoGame.Extended/Particles/Serialization/ProfileJsonConverter.cs, source/MonoGame.Extended/Serialization/Json/RangeJsonConverter.cs, source/MonoGame.Extended/Serialization/Json/RectangleFJsonConverter.cs, source/MonoGame.Extended/Serialization/Json/Size2JsonConverter.cs, source/MonoGame.Extended/Serialization/Json/SizeJsonConverter.cs, source/MonoGame.Extended/Serialization/Json/TextureRegionService.cs, source/MonoGame.Extended/Serialization/Json/ThicknessJsonConverter.cs, source/MonoGame.Extended/Serialization/Json/Utf8JsonReaderExtensions.cs, source/MonoGame.Extended/Serialization/Json/Vector2JsonConverter.cs
This resolves issue #936 that was caused due to a regression when switching from Newtonsoft.Json to System.Text.Json in commit https://github.com/craftworkgames/MonoGame.Extended/commit/d008b1bd4104be237a156a15a46e5e11353bc262.
Issue was caused due to a recursive loop occurring in the `ProfileJsonConverter` which would eventually lead to a `StackOverflowException`.
The `ProfileJsonConverter` has been updated to handle each `Profile` type scenario expected from a *.particle* file.
=> Read particle file issue

source/MonoGame.Extended/Graphics/NinePatch.cs
=> Fix bug when using `NinePatch` with `Texture2DRegion`.

source/MonoGame.Extended/BitmapFonts/BitmapFont.cs, source/MonoGame.Extended/Content/BitmapFonts/BitmapFontFileReader.cs, tests/MonoGame.Extended.Tests/BitmapFonts/BitmapFontFileReaderTests.cs
Fixes KNI web builds when using `BitmapFont`.
Resolves #944
=> `BitmapFont` now always loads from `TitleContainer`.
